package com.tungtt.bigdata.models

import org.apache.spark.sql.types.{DecimalType, IntegerType, StringType, StructType}

case class SyncData[T](var payload: Payload[T]) {

}

case class Payload[T](var after: T) {

}

object SyncDataStruct {
  val phieuGuiStruct: StructType = new StructType()
    .add("payload", new StructType()
      .add("after", new StructType()
        .add("id_phieugui", IntegerType, nullable = true)
        .add("ma_phieugui", StringType, nullable = true)
        .add("gui_trongnuoc", IntegerType, nullable = true)
        .add("ma_khgui", StringType, nullable = true)
        .add("ten_khgui", StringType, nullable = true)
        .add("diachi_khgui", StringType, nullable = true)
        .add("tel_khgui", StringType, nullable = true)
        .add("ma_buucuc_goc", StringType, nullable = true)
        .add("ten_khnhan", StringType, nullable = true)
        .add("diachi_khnhan", StringType, nullable = true)
        .add("tel_khnhan", StringType, nullable = true)
        .add("ma_buucuc_phat", StringType, nullable = true)
        .add("ma_vung_phat", StringType, nullable = true)
        .add("ma_dv_viettel", StringType, nullable = true)
        .add("ma_dv_ketnoi", IntegerType, nullable = true)
        .add("noi_dung", StringType, nullable = true)
        .add("ngay_gui_bp", StringType, nullable = true)
        .add("tong_tien", IntegerType, nullable = true)
        .add("ty_gia", IntegerType, nullable = true)
        .add("da_thanh_toan", IntegerType, nullable = true)
        .add("ngay_nhap_may", StringType, nullable = true)
        .add("nguoi_nhap_may", IntegerType, nullable = true)
        .add("phu_phi", IntegerType, nullable = true)
        .add("phu_phi_comment", IntegerType, nullable = true)
        .add("tong_tien_nguyen_te", DecimalType(0,9), nullable = true)
        .add("tong_vat", DecimalType(0,9), nullable = true)
        .add("thue_suat_vat", IntegerType, nullable = true)
        .add("ma_phieu_ketnoi", StringType, nullable = true)
        .add("tong_cuoc_vnd", DecimalType(0,9), nullable = true)
        .add("trangthai_congno", IntegerType, nullable = true)
        .add("ma_loai_hanghoa", StringType, nullable = true)
        .add("ma_kieu_thanhtoan", StringType, nullable = true)
        .add("ma_khnhan", StringType, nullable = true)
        .add("dv_connect", StringType, nullable = true)
        .add("phuphi_xangdau", IntegerType, nullable = true)
        .add("phuphi_khac", IntegerType, nullable = true)
        .add("gia_goc", IntegerType, nullable = true)
        .add("gia_dieuchinh", IntegerType, nullable = true)
        .add("lan_dieuchinh", IntegerType, nullable = true)
        .add("nguoi_dieuchinh", StringType, nullable = true)
        .add("ngay_dieuchinh", StringType, nullable = true)
        .add("phi_dv_dacbiet", IntegerType, nullable = true)
        .add("manual", IntegerType, nullable = true)
        .add("trong_luong", IntegerType, nullable = true)
        .add("dieuchinhgia", IntegerType, nullable = true)
        .add("hanh_trinh", StringType, nullable = true)
        .add("khoaso_dt", IntegerType, nullable = true)
        .add("ma_tuyenbuuta", IntegerType, nullable = true)
        .add("id_quanhuyen", IntegerType, nullable = true)
        .add("id_location", StringType, nullable = true)
        .add("ma_tuyen_qp", StringType, nullable = true)
        .add("ma_quanhuyen", StringType, nullable = true)
        .add("id_phuongxa1111", StringType, nullable = true)
        .add("ten_tuyen", StringType, nullable = true)
        .add("id_tuyen", StringType, nullable = true)
        .add("ma_phuongxa", StringType, nullable = true)
        .add("khai_gia", IntegerType, nullable = true)
        .add("thu_ho", IntegerType, nullable = true)
        .add("vtp_id", IntegerType, nullable = true)
        .add("ma_kh_vtp", StringType, nullable = true)
        .add("id_buucuc", IntegerType, nullable = true)
        .add("id_khachhang", IntegerType, nullable = true)
        .add("id_shop", IntegerType, nullable = true)
        .add("id_doitac", IntegerType, nullable = true)
        .add("id_nguon", IntegerType, nullable = true)
        .add("loai_pg", IntegerType, nullable = true)
        .add("kpi_tg_qd", StringType, nullable = true)
        .add("order_id", IntegerType, nullable = true)
        .add("order_num", IntegerType, nullable = true)
        .add("tl_thuc", StringType, nullable = true)
        .add("qd_dai", StringType, nullable = true)
        .add("qd_rong", StringType, nullable = true)
        .add("qd_cao", StringType, nullable = true)
        .add("tl_quydoi", StringType, nullable = true)
        .add("id_street", StringType, nullable = true)
        ,
        nullable = true),
      nullable = true)
}